# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11glFFy-JD6HmaYfzz3lzgf2FD94Tt8Ge
"""

from google.colab import files
uploaded = files.upload()

from google.colab import files
uploaded = files.upload()

"""Loading of Data"""

import pandas as pd
details = pd.read_csv('Details.csv')
orders = pd.read_csv('Orders.csv')

"""Data Preprocessing"""

# Check for missing values
print(details.isnull().sum())
print(orders.isnull().sum())

details.columns.to_list()

orders.columns.to_list()

details.describe()

"""Merging of two data set

"""

merged_data = pd.merge(details, orders, on='Order ID', how='inner')

# Display the merged table
print(merged_data.head())

"""Analyzing merged data"""

#Total Sales and Profit by Category
category_analysis = merged_data.groupby('Category').agg({'Amount': 'sum', 'Profit': 'sum'})

#Sales Performance by State
state_sales = merged_data.groupby('State')['Amount'].sum().sort_values(ascending=False)

#Top Customers by Total Amount
top_customers = merged_data.groupby('CustomerName')['Amount'].sum().sort_values(ascending=False).head(10)

#Popular Payment Modes
payment_mode_count = merged_data['PaymentMode'].value_counts()

"""Visualization"""

# Sales by Category (Bar Chart)
import matplotlib.pyplot as plt

category_analysis['Amount'].plot(kind='bar', title='Total Sales by Category', color='skyblue')
plt.ylabel('Total Sales')
plt.show()

""" Profit by Sub-Category (Pie Chart)

"""

sub_category_profit = merged_data.groupby('Sub-Category')['Profit'].sum()
sub_category_profit = sub_category_profit[sub_category_profit >= 0]
sub_category_profit.plot(kind='pie', autopct='%1.1f%%', title='Profit Distribution by Sub-Category')
plt.show()